version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: judge0-ide-app
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USER=${DB_USER:-moodle_user}
      - DB_PASSWORD=${DB_PASSWORD:-moodle_password}
      - DB_NAME=${DB_NAME:-moodle}
      - DB_SOCKET=${DB_SOCKET:-/var/run/mysqld/mysqld.sock}
      - DB_DEBUG=${DB_DEBUG:-false}
    volumes:
      - ${MOODLE_DB_MOUNT:-/mnt/moodle-db}:/moodle-db:ro
    networks:
      - moodle-network
    restart: unless-stopped

networks:
  moodle-network:
    driver: bridge
