version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: judge0-ide-app
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USER=${DB_USER:-moodle_user}
      - DB_PASSWORD=${DB_PASSWORD:-moodle_password}
      - DB_NAME=${DB_NAME:-moodle}
      - DB_DEBUG=${DB_DEBUG:-false}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-muadmin2025}
      - ADMIN_USER_ID=${ADMIN_USER_ID:-admin-1}
      - ADMIN_FIRSTNAME=${ADMIN_FIRSTNAME:-Admin}
      - ADMIN_LASTNAME=${ADMIN_LASTNAME:-User}
      - DEBUG_TOKEN=${DEBUG_TOKEN:-debug123}
    volumes:
      - ${MOODLE_DB_MOUNT:-/mnt/moodle-db}:/moodle-db:ro
    networks:
      - moodle-network
    restart: unless-stopped

networks:
  moodle-network:
    driver: bridge
