services:
  # Your Node.js application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: judge0-ide-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres-moodle # This should be your Moodle DB container name
      - DB_PORT=5432
      - DB_USER=moodle_user # Replace with your actual DB username
      - DB_PASSWORD=moodle_password # Replace with your actual DB password
      - DB_NAME=moodle
    networks:
      - moodle-network
    depends_on:
      - postgres-moodle
    restart: unless-stopped

  # This references your existing PostgreSQL container
  # If your PostgreSQL is already running in another docker-compose setup,
  # you can use the 'external_links' approach instead
  postgres-moodle:
    image: postgres:14 # Make sure this matches your existing Postgres version
    container_name: postgres-moodle # Should match your existing container name
    # Comment these out if your PostgreSQL container is already running
    environment:
      POSTGRES_USER: moodle_user
      POSTGRES_PASSWORD: moodle_password
      POSTGRES_DB: moodle
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - moodle-network
    restart: unless-stopped

networks:
  moodle-network:
    driver: bridge

volumes:
  postgres-data:
